---
name: Test Code

# See https://github.com/actions/virtual-environments
# Doesn't compile on macos - IO::AIO doesn't import

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-2022
          - windows-2019
        perl: ['5.36', '5.34', '5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn --skip-satisfied ExtUtils::PL2Bat File::Spec ExtUtils::MakeMaker LWP::Simple::WithCache
          cpanm -iqn --skip-satisfied Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Carp Test::Pod::Coverage
          cpanm -iqn --skip-satisfied --installdeps --notest .
      - name: Run Tests
        run: prove -l -b t
        env:
          AUTHOR_TESTING: 1
